<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Jessica Martin" />
    <meta name="description" content="Describe your website">
    <link rel="shortcut icon" type="image/x-icon" href="../img/favicon.ico">
    <title>Modeling, Testing, and Classification</title>
    <meta name="generator" content="Hugo 0.70.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../blog/">BLOG</a></li>
        
        <li><a href="../projects/">PROJECTS</a></li>
        
        <li><a href="../resume.pdf">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../project2/">Modeling, Testing, and Classification</a></strong>
          </h3>
        </div>
        <div class="blog-title">
          <h4>
          January 1, 0001
            &nbsp;&nbsp;
            
          </h4>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>This dataset, “heart”, was found on kaggle.com. The data was collected in a hospital from 303 willing participants; the goal was to find possible trends in order to predict certain cardiovascular events or find any clear indications of heart health. It originially featured a set of 14 attributes that play a role in heart disease. Some of these variables were removed and some were renamed in order to create a dataset that is readily usable for this project. The remaining eight variables are as follows: “age”, measured in years; “sex”, with 1 representing male and 0 female; “chest.pain”, measured from 0 (absence of pain) to 3 (intense pain); “rest.BP”, the resting systolic blood pressure upon admission (measured in mmHg); “chol”, cholesterol measured in mg/dL; “maxHR”, maximum heart rate acheived (measured in beats/min); “ex.angina”, whether or not angina is induced upon exercising, with 0 representing the absence of and 1 representing angina; and “condition”, with 3 representing normal, 1 representing a fixed defect, and 2 representing a reversible defect in the heart.</p>
<pre class="r"><code>heart &lt;- read.csv(&quot;~/heart.csv&quot;)

library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>heart&lt;-heart%&gt;%select(-restecg, -oldpeak, -slope, -ca, -target, -fbs)%&gt;%rename(condition=thal, chest.pain=cp, maxHR=thalach, ex.angina=exang, rest.BP=trestbps)

heart$sex&lt;-factor(heart$sex, levels=c(1,0))

heart%&gt;%head</code></pre>
<pre><code>##   age sex chest.pain rest.BP chol maxHR ex.angina condition
## 1  63   1          3     145  233   150         0         1
## 2  37   1          2     130  250   187         0         2
## 3  41   0          1     130  204   172         0         2
## 4  56   1          1     120  236   178         0         2
## 5  57   0          0     120  354   163         1         2
## 6  57   1          0     140  192   148         0         1</code></pre>
<pre class="r"><code>heart%&gt;%nrow</code></pre>
<pre><code>## [1] 303</code></pre>
</div>
<div id="manova" class="section level1">
<h1>1. MANOVA</h1>
<pre class="r"><code>manova&lt;-manova(cbind(rest.BP, maxHR, chol, age)~chest.pain, data=heart)
summary(manova)</code></pre>
<pre><code>##             Df Pillai approx F num Df den Df    Pr(&gt;F)    
## chest.pain   1 0.1011   8.3787      4    298 2.038e-06 ***
## Residuals  301                                            
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>First, a MANOVA was run on the “heart” dataset, in order to determine if any of the numeric variables in the dataset (resting BP, max HR, cholesterol, and age) significantly differed among the categories of chest pain (0,1,2,3). It was found that the overall MANOVA test was significant (Pillai trace=0.10, pseudo F(4,298), p-value&lt;0.0001), meaning that at least one of the dependent variables differed among the groups of chest pain. Thus, follow-up univariate ANOVAs were conducted for each variable.</p>
<pre class="r"><code>summary.aov(manova)</code></pre>
<pre><code>##  Response rest.BP :
##              Df Sum Sq Mean Sq F value Pr(&gt;F)
## chest.pain    1    211  210.54  0.6838 0.4089
## Residuals   301  92681  307.91               
## 
##  Response maxHR :
##              Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## chest.pain    1  13860 13859.9  28.854 1.564e-07 ***
## Residuals   301 144583   480.3                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response chol :
##              Df Sum Sq Mean Sq F value Pr(&gt;F)
## chest.pain    1   4798  4798.3  1.7908 0.1818
## Residuals   301 806503  2679.4               
## 
##  Response age :
##              Df  Sum Sq Mean Sq F value Pr(&gt;F)
## chest.pain    1   117.4 117.408  1.4254 0.2335
## Residuals   301 24792.9  82.369</code></pre>
<p>Of the four variables, only max HR was significantly different across at least one of the categories of chest pain, F(1,301)=28.854, p&lt;0.0001. The next step was to run post hoc t tests to determine which categories of chest pain differed in terms of max HR.</p>
<pre class="r"><code>pairwise.t.test(heart$maxHR, heart$chest.pain, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  heart$maxHR and heart$chest.pain 
## 
##   0       1      2     
## 1 1.2e-09 -      -     
## 2 3.2e-07 0.0713 -     
## 3 0.0013  0.2273 0.9443
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>0.05/11</code></pre>
<pre><code>## [1] 0.004545455</code></pre>
<p>The t tests revealed that patients who had no chest pain (value 0) significantly differed in max HR from those who rated their chest pain a 1, as well as from those who rated their chest pain a 2, as well as from those who rated their chest pain a 3. There was no significant difference between any of the other groups. Because 1 MANOVA, 4 ANOVAs, and 6 t tests were run, the probability of committing type 1 error is high. In order to control for Type I error rates, the Bonferroni correction method was utilized. The adjusted level of significance was found to be 0.0045. This did not affect any of the previous conclusions of significance. It is important to add that there are many assumptions to meet when running a MANOVA test. There were no tests run to determine multivariate normality of the dependent variables, homogeneity, linear relationships, outliers, or multicollineariity. Therefore, it is unlikely that all of these assumptions were met.</p>
</div>
<div id="randomization" class="section level1">
<h1>2. RANDOMIZATION</h1>
<p>In order to conduct a randomization test on this dataset, null and alternative hypotheses had to be constructed. Null hypothesis: Cholesterol levels are the same for each heart condition. Alternative hypothesis: Cholesterol levels are not the same for each heart condition.</p>
<pre class="r"><code>heart%&gt;%group_by(condition)%&gt;%filter(condition %in% c(0, 3))%&gt;%summarize(means=mean(chol))%&gt;%
  summarize(&#39;mean_diff&#39;=diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   mean_diff
##       &lt;dbl&gt;
## 1      40.2</code></pre>
<pre class="r"><code>perm1&lt;-data.frame(condition=heart$condition, chol=sample(heart$chol))

perm1%&gt;%group_by(condition)%&gt;%filter(condition %in% c(0, 3))%&gt;%summarize(means=mean(chol))%&gt;%summarize(&#39;mean_diff&#39;=diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   mean_diff
##       &lt;dbl&gt;
## 1      36.7</code></pre>
<pre class="r"><code>perm2&lt;-data.frame(condition=heart$condition, chol=sample(heart$chol))

perm2%&gt;%group_by(condition)%&gt;%filter(condition %in% c(0, 3))%&gt;%summarize(means=mean(chol))%&gt;%summarize(&#39;mean_diff&#39;=diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   mean_diff
##       &lt;dbl&gt;
## 1     -2.54</code></pre>
<pre class="r"><code>perm3&lt;-data.frame(condition=heart$condition, chol=sample(heart$chol))

perm3%&gt;%group_by(condition)%&gt;%filter(condition %in% c(0, 3))%&gt;%summarize(means=mean(chol))%&gt;%summarize(&#39;mean_diff&#39;=diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   mean_diff
##       &lt;dbl&gt;
## 1      34.9</code></pre>
<pre class="r"><code>rand_dist&lt;-vector()

for(i in 1:5000){
new&lt;-data.frame(chol=sample(heart$chol),condition=heart$condition) 
rand_dist[i]&lt;-mean(new[new$condition==0,]$chol)-
mean(new[new$condition==3,]$chol)}
{hist(rand_dist, main=&quot;&quot;, ylab=&quot;&quot;); abline(v=40.2,col=&quot;red&quot;)}</code></pre>
<p><img src="../project2_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>mean(rand_dist&gt;40.2 | rand_dist&lt; -40.2) </code></pre>
<pre><code>## [1] 0.255</code></pre>
<p>After performing the randomization test and visualizing it with a histogram, the null hypothesis cannot be rejected, due to a non-significant two-tailed p-value (0.2484). Thus, it can be concluded that cholesterol levels are the same for each heart condition.</p>
</div>
<div id="linear-regression" class="section level1">
<h1>3. LINEAR REGRESSION</h1>
<p>A linear regression was then performed in order to predict a response variable, cholesterol, from three other variables and their interactions–sex, resting BP, and condition. The numeric values (cholesterol and resting BP) were first mean-centered and renamed as “chol_c” and “rest.BP_c”.</p>
<pre class="r"><code>heart1&lt;-heart
heart1$rest.BP_c&lt;-heart1$rest.BP-mean(heart1$rest.BP)
heart1$chol_c&lt;-heart1$chol-mean(heart1$chol)

fit&lt;-lm(chol_c~sex*rest.BP_c*condition, data=heart1)
summary(fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = chol_c ~ sex * rest.BP_c * condition, data = heart1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -123.443  -32.904   -2.203   27.734  232.410 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)              -22.6184    12.9454  -1.747 0.081642 .  
## sex0                     -76.0041    30.5081  -2.491 0.013278 *  
## rest.BP_c                 -0.4647     0.8189  -0.568 0.570789    
## condition                  6.5222     5.2004   1.254 0.210770    
## sex0:rest.BP_c             4.8642     1.5276   3.184 0.001607 ** 
## sex0:condition            48.1249    14.0038   3.437 0.000674 ***
## rest.BP_c:condition        0.2679     0.3149   0.851 0.395515    
## sex0:rest.BP_c:condition  -2.1356     0.6618  -3.227 0.001393 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 49.18 on 295 degrees of freedom
## Multiple R-squared:  0.1206, Adjusted R-squared:  0.09975 
## F-statistic: 5.781 on 7 and 295 DF,  p-value: 2.732e-06</code></pre>
<p>The intercept represents the reference group. In this case, the intercept represents the predicted cholesterol value for a female (value of 0) with average resting blood pressure and a normal heart condition, as -98.62 mg/dL. Each coefficient represents to what degree the intercept will go up or down for every one-unit increase in each. Because there are so many coefficients listed, I will only explain a few. For example, the coefficient “age” represents an increase of 76 mg/dL in cholesterol if the subject is male, while controlling for all other variables. Likewise, the “rest.BP_c” coefficient shows that for each one unit increase in resting blood pressure, there is an increase of 4.4 mg/dL of cholesterol, regardless of all other variables. For the interaction coefficient “sex:condition”, when controlling for resting BP, the slope for sex on cholesterol is 48.12 lower for those with heart conditions, compared to those with a normal heart condition.</p>
<div id="regression-plot" class="section level3">
<h3>REGRESSION PLOT</h3>
<pre class="r"><code>library(ggplot2)
hearts&lt;-heart1
hearts$sex&lt;-factor(hearts$sex, levels=c(1,0))
ggplot(hearts, aes(x=rest.BP_c, y=chol_c, group=sex))+
  geom_point(aes(color=sex)) + xlab(&quot;Resting BP&quot;) +ylab(&quot;Cholesterol&quot;)</code></pre>
<p><img src="../project2_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
</div>
<div id="assumptions" class="section level3">
<h3>ASSUMPTIONS</h3>
<pre class="r"><code>#linearity
resids&lt;-fit$residuals
fitvals&lt;-fit$fitted.values
ggplot()+geom_qq(aes(sample=resids))+geom_qq_line(aes(sample=resids)) </code></pre>
<p><img src="../project2_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code>#normality
ggplot()+geom_histogram(aes(resids, color=&quot;blue&quot;), bins=10)+ theme(legend.position=&quot;none&quot;)</code></pre>
<p><img src="../project2_files/figure-html/unnamed-chunk-8-2.png" width="672" /></p>
<pre class="r"><code>ks.test(resids, &quot;pnorm&quot;, mean=0, sd(resids))</code></pre>
<pre><code>## Warning in ks.test(resids, &quot;pnorm&quot;, mean = 0, sd(resids)): ties should not be
## present for the Kolmogorov-Smirnov test</code></pre>
<pre><code>## 
##  One-sample Kolmogorov-Smirnov test
## 
## data:  resids
## D = 0.041229, p-value = 0.6816
## alternative hypothesis: two-sided</code></pre>
<pre class="r"><code>#homoskedasticity
library(sandwich); library(lmtest)</code></pre>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<pre class="r"><code>bptest(fit)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 33.266, df = 7, p-value = 2.362e-05</code></pre>
<p>As can be seen above, the first plot shows that the assumption of linearity is met. The second plot shows that the assumption of normality is met. Additionally, a KS test was run and the p-value was not significant, meaning that the assumption of normality is definitely met. Lastly, to test for homoskedasticity, the BP test was utilized, giving a significant p-value, meaning that this assumption was not met.</p>
</div>
<div id="robust-standard-errors" class="section level3">
<h3>ROBUST STANDARD ERRORS</h3>
<pre class="r"><code>coeftest(fit) </code></pre>
<pre><code>## 
## t test of coefficients:
## 
##                           Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)              -22.61835   12.94543 -1.7472 0.0816418 .  
## sex0                     -76.00413   30.50806 -2.4913 0.0132779 *  
## rest.BP_c                 -0.46473    0.81887 -0.5675 0.5707887    
## condition                  6.52224    5.20040  1.2542 0.2107695    
## sex0:rest.BP_c             4.86416    1.52762  3.1841 0.0016071 ** 
## sex0:condition            48.12492   14.00383  3.4366 0.0006738 ***
## rest.BP_c:condition        0.26792    0.31487  0.8509 0.3955146    
## sex0:rest.BP_c:condition  -2.13556    0.66182 -3.2268 0.0013927 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>coeftest(fit, vcov=vcovHC(fit)) </code></pre>
<pre><code>## 
## t test of coefficients:
## 
##                           Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)              -22.61835   11.35377 -1.9921  0.04728 *
## sex0                     -76.00413   71.48780 -1.0632  0.28857  
## rest.BP_c                 -0.46473    0.68242 -0.6810  0.49641  
## condition                  6.52224    4.57414  1.4259  0.15496  
## sex0:rest.BP_c             4.86416    3.05538  1.5920  0.11246  
## sex0:condition            48.12492   34.99971  1.3750  0.17017  
## rest.BP_c:condition        0.26792    0.26162  1.0241  0.30663  
## sex0:rest.BP_c:condition  -2.13556    1.47353 -1.4493  0.14832  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Above, the normal-theory standard errors of the regression are compared to the robust standard errors run on the same regression models. The robust standard errors are quite a bit larger than the normal-theory SEs; in fact, all of the coefficient values were significant with the normal SEs, but with the robust SEs, there is no longer a single significant coefficient. The proportion of variation in cholesterol explained by this model is 0.09975. This is the adjusted R-squared value from summary(fit).</p>
</div>
</div>
<div id="bootstrapped-standard-errors" class="section level1">
<h1>4. BOOTSTRAPPED STANDARD ERRORS</h1>
<pre class="r"><code>samp_bse&lt;-replicate(5000, { 
  boot_dat &lt;- sample_frac(heart1, replace=T)
  fitbse&lt;-lm(chol_c~sex*rest.BP*condition, data=boot_dat)
  coef(fitbse)})
samp_bse%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>##   (Intercept)     sex0   rest.BP condition sex0:rest.BP sex0:condition
## 1    90.34791 449.2832 0.6683838  34.69663     3.104871        220.042
##   rest.BP:condition sex0:rest.BP:condition
## 1          0.256683               1.510464</code></pre>
<p>In comparison to the normal standard errors, many of the bootstrapped standard errors are much, much higher–namely, the intercept, sex, condition, and sex:condition coefficients. The other coefficients are reasonably close to the robust standard errors. However, each one is higher than its corresponding robust standard error, so it can be concluded that none of the bootstrapped standard errors are significant.</p>
</div>
<div id="logistic-regression" class="section level1">
<h1>5. LOGISTIC REGRESSION</h1>
<pre class="r"><code>library(lmtest)
heart1$maxHR_c&lt;-heart1$maxHR-mean(heart1$maxHR)
fitlin&lt;-glm(ex.angina~maxHR+sex+chest.pain, data=heart, family=binomial)
coeftest(fitlin)</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##               Estimate Std. Error z value  Pr(&gt;|z|)    
## (Intercept)  4.5961551  0.9809196  4.6856 2.792e-06 ***
## maxHR       -0.0305405  0.0066808 -4.5714 4.844e-06 ***
## sex0        -0.6178638  0.3136634 -1.9698   0.04886 *  
## chest.pain  -0.8234645  0.1613775 -5.1027 3.348e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coef(fitlin))</code></pre>
<pre><code>## (Intercept)       maxHR        sex0  chest.pain 
##  99.1025438   0.9699212   0.5390948   0.4389084</code></pre>
<p>The intercept represents the reference group; specifically, the odds of a male patient with an average heart rate and no chest pain NOT experiencing angina upon exercising is 99.1. For the maxHR coefficient, when controlling for sex and chest pain, the odds of not experiencing angina upon exercising increases by a factor of 0.9699. For the sex0 coefficient, when controlling for maxHR and chest pain, the odds of not experiencing angina increases by a factor of 0.539. Finally, for the chest.pain coefficient, when controlling for maxHR and sex, the odds of not experiencing angina increase by a factor of 0.439.</p>
<div id="confusion-matrix" class="section level3">
<h3>CONFUSION MATRIX</h3>
<pre class="r"><code>library(tidyr)
probs1&lt;-predict(fitlin, type=&quot;response&quot;)
table(predict=as.numeric(probs1&gt;0.5), truth=heart1$ex.angina)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict   0   1 Sum
##     0   178  43 221
##     1    26  56  82
##     Sum 204  99 303</code></pre>
<pre class="r"><code>#Sensitivity (TPR)
56/99</code></pre>
<pre><code>## [1] 0.5656566</code></pre>
<pre class="r"><code>#specificity (TNR)
178/204</code></pre>
<pre><code>## [1] 0.872549</code></pre>
<pre class="r"><code>#precision (PPV)
56/82</code></pre>
<pre><code>## [1] 0.6829268</code></pre>
<pre class="r"><code>#Accuracy 
(56+178)/303</code></pre>
<pre><code>## [1] 0.7722772</code></pre>
</div>
<div id="density-plot" class="section level3">
<h3>DENSITY PLOT</h3>
<pre class="r"><code>library(ggplot2)
heart1$ex.angina&lt;-factor(heart1$ex.angina, levels=c(1,0))
heart1$logit&lt;-predict(fitlin,type=&quot;link&quot;)
heart1%&gt;%ggplot()+geom_density(aes(logit, color=ex.angina, fill=ex.angina), alpha=.4)+geom_rug(aes(logit, color=ex.angina))+theme(legend.position=c(.85,.85))+geom_vline(xintercept=0)+xlab(&quot;logit (log-odds)&quot;)+
geom_text(x=-0.7,y=.2,label=&quot;TN = 178&quot;)+ geom_text(x=-1.5,y=.008,label=&quot;FN = 26&quot;)+
geom_text(x=1,y=.006,label=&quot;FP = 43&quot;)+
geom_text(x=1.8,y=.2,label=&quot;TP = 56&quot;)</code></pre>
<p><img src="../project2_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
</div>
<div id="roc-auc" class="section level3">
<h3>ROC &amp; AUC</h3>
<pre class="r"><code>library(plotROC)

heartroc&lt;-heart1%&gt;%mutate(y=ifelse(ex.angina==0,0,1))

heartroc$prob&lt;-predict(fitlin,type=&quot;response&quot;)

ROCplot&lt;-ggplot(heartroc)+geom_roc(aes(d=y, m=prob), n.cuts=0)

ROCplot</code></pre>
<p><img src="../project2_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.8067439</code></pre>
<p>This ROC plot is far from perfect, but it is not terrible. According to the rules of thumb for AUC, this model fits in the fair/good category, with an AUC value of 0.8067.</p>
</div>
<div id="fold-cv" class="section level3">
<h3>10-FOLD CV</h3>
<pre class="r"><code>heart2&lt;-heart1
set.seed(1234)
k=10

data&lt;-heart2[sample(nrow(heart2)),]
folds&lt;-cut(seq(1:nrow(heart2)), breaks=k, labels=F)

class_diag &lt;- function(probs,truth){
tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
acc=sum(diag(tab))/sum(tab)
sens=tab[2,2]/colSums(tab)[2]
spec=tab[1,1]/colSums(tab)[1]
ppv=tab[2,2]/rowSums(tab)[2]
if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
ord&lt;-order(probs, decreasing=TRUE)
probs &lt;- probs[ord]; truth &lt;- truth[ord]
TPR=cumsum(truth)/max(1,sum(truth))
FPR=cumsum(!truth)/max(1,sum(!truth))
dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
n &lt;- length(TPR)
auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
data.frame(acc,sens,spec,ppv,auc)
} 

diags&lt;-NULL
for(i in 1:k){
  train&lt;-data[folds!=i,]
  test&lt;-data[folds==i,]
  truth&lt;-test$ex.angina
  
  fitk&lt;-glm(ex.angina~maxHR_c+sex+chest.pain, data=heart2, family=&quot;binomial&quot;)
  
  probsk&lt;-predict(fitk, newdata=test, type=&quot;response&quot;)
  
  diags&lt;-rbind(diags, class_diag(probsk, truth))
}
summarize_all(diags, mean)</code></pre>
<pre><code>##         acc      sens      spec       ppv       auc
## 1 0.7722581 0.8718864 0.5619414 0.8014469 0.8015514</code></pre>
<p>The average out-of-sample accuracy was found to be 0.772, the sensitivity 0.872, and the recall 0.801. This represents a fair/good model but it could be better.</p>
</div>
</div>
<div id="lasso" class="section level1">
<h1>LASSO</h1>
<pre class="r"><code>library(glmnet)</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## 
## Attaching package: &#39;Matrix&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:tidyr&#39;:
## 
##     expand, pack, unpack</code></pre>
<pre><code>## Loading required package: foreach</code></pre>
<pre><code>## Loaded glmnet 2.0-16</code></pre>
<pre class="r"><code>y&lt;-as.matrix(heart2$ex.angina)
x&lt;-model.matrix(ex.angina~., data=heart2)[,-1]
x&lt;-scale(x)
cv&lt;-cv.glmnet(x,y,family=&quot;binomial&quot;)
lasso&lt;-glmnet(x,y,family=&quot;binomial&quot;, lambda=cv$lambda.1se)
coef(lasso)</code></pre>
<pre><code>## 12 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                     s0
## (Intercept) -0.7967525
## age          .        
## sex0         .        
## chest.pain   .        
## rest.BP      .        
## chol         .        
## maxHR        .        
## condition    .        
## rest.BP_c    .        
## chol_c       .        
## maxHR_c      .        
## logit        0.6775472</code></pre>
<p>After running a LASSO regression, the only variables retained are “chest.pain”, “maxHR”, and “condition”.</p>
<div id="fold-cv-1" class="section level2">
<h2>10-FOLD CV</h2>
<pre class="r"><code>set.seed(1234)
k=10

data2&lt;-heart2[sample(nrow(heart2)),]
folds2&lt;-cut(seq(1:nrow(heart2)), breaks=k, labels=F)

diags2&lt;-NULL
for(i in 1:k){
  train2&lt;-data2[folds!=i,]
  test2&lt;-data2[folds==i,]
  truth2&lt;-test2$ex.angina
  
  fit3&lt;-glm(ex.angina~maxHR_c+sex+chest.pain, data=heart2, family=&quot;binomial&quot;)
  
  probs3&lt;-predict(fit3, newdata=test2, type=&quot;response&quot;)
  
  diags2&lt;-rbind(diags2, class_diag(probs3, truth2))
}
summarize_all(diags2, mean)</code></pre>
<pre><code>##         acc      sens      spec       ppv       auc
## 1 0.7722581 0.8718864 0.5619414 0.8014469 0.8015514</code></pre>
<p>After running the ten-fold cross validation, it can be seen that the accuracy of this model is the same as the logistic regression run in part 5.</p>
</div>
</div>

              <hr>
              <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../js/docs.min.js"></script>
<script src="../js/main.js"></script>

<script src="../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
